language: php
php: [5.6]
sudo: false
branches:
- master

install:
- echo | pecl install channel://pecl.php.net/yaml-1.1.1

script: php make.php

after_success:

env:
  global:
    - secure:
