---

###########
## POWER ##
###########
## Power affects how many chunks a faction can claim. Power is not taken when a chunk is claimed, but a faction cannot claim more chunks if the power is not high enough.
## Power of a faction depends on its members. When it loses members, its power drops.
# The power required for a faction to claim a chunk
power required to claim a chunk: 1000
# The power of a player increases every hour he is online (not necessarily a continuous hour)
power gained per online hour: 50
# The power of a player decreases if he has not been online that day ("day" calculated in the server's timezone)
power lost per offline FULL day: 40
# The power of a player increases when he kills a player or a mob
power gained per player kill: 60
power gained per mob kill:
  - name: default
    value: 5
  - name: zombie pigman
    value: 40
  - name: creeper
    value: 40
  - name: skeleton
    value: 30
  - name: zombie
    value: 20
# This counts the number of TINY slimes killed.
  - name: slime
    value: 2
# The power of a player decreases when he dies
power lost per death:
  - name: default
    value: 30
  - name: killed by player
    value: 50
  - name: killed by monster
    value: 50
  - name: drowning
    value: 35
  - name: monster
    value: 45
  - name: explosion
    value: 35
  - name: lava
    value: 40
  - name: burning
    value: 30
  - name: falling
    value: 10

############
## GAMEPLAY ##
############
## When a faction's power drops too low that no more chunks can be claimed, and in fact its power would not allow it to claim so many chunks, "power overdraft" occurs.
# When sieging is enabled, if a faction has power overdraft, other factions can siege any marginary chunks of the faction by walking in the chunk centre and claim the chunk like from wilderness.
enable sieging: false

## Members of other factions can only siege the marginary chunk if they walk inside enough. Define "inside enough" here.
# If the player is within this number of blocks from the chunk centre, allow them to siege the chunk.
siege radius: 4

# PocketFactions generates a world if the world of a faction's claimed chunk doesn't exist. If you want to specify the seed, put it below.
level generation seed: null
...
