---

# CONFIGURATION FILE FOR POCKETFACTIONS
# Unless otherwise specified, all the file paths required in this config file must be relative to the plugin's data folder (the directory this config file is in)

# This lets you select the type of data providers to use for PF (PocketFactions).
dataProviders:
  # The "factions" data provider saves the information about factions and faction members, as well as their relationship.
  factions:
    # available types:
    # > mysql
    # > sqlite3
    # Note: MySQL will be run asynchronously, so it will not cause server lag.
    # Also note that if the data on MySQL are changed externally, it is undefined whether they will be loaded immediately or not, but they will be loaded after server restart (if the plugin didn't somehow overwrite it)
    type: mysql

    # If you chose "mysql", please configure these:
    mysql:
      # host address of the database. "localhost" is accepted.
      host: "127.0.0.1"
      # note: you are discouraged to use "root" as the user.
      username: "root"
      # password to the database for the account in "username". Remember not to share this file!
      password: ""
      # schema, or "database", to use for PocketFactions
      schema: "pf"
      # port that the database is hosted on.
      port: 3306

    # if you chose "sqlite3", please configure these:
    sqlite3:
      # the path to save the database
      path: factions.db

# This section is about how PocketFactions connects with other plugins.
integrations:
  # supported: none, SimpleAuth
  auth: none

# This section is about the core mechanism of PocketFactions
mechanism:
  # This defines the plot margin size. If this is "8", each plot will be 8x8 blocks big.
  # This MUST be one of "1", "2", "4", "8" or "16"!!! If you put invalid values, PocketFactions will pick the default value.
  # WARNING: Updating this will not take effect unless you reset the database.
  plotSize: 8

  # This defines default mechanisms in a faction when a new faction is founded.
  defaults:
    # The default "ranks" existing in a faction
    # You can find a full list of "accesses" that a rank can have, at this website:
    #
...
