---

################
## MUST SETUP ##
################
faction worlds:
- >>>> this is an example world <<<<
- >>>> please replace these worlds <<<<

###########
## POWER ##
###########
#### Power affects how many chunks a faction can claim.
#### Power is not taken when a chunk is claimed, but a faction cannot claim more chunks if the power is not high enough.
#### Reputation
## Reputation is a modifier of power.
# The reputation power increases for the following relations
relation reputations modifiers:
  enemy: -100
  truce: 25
  ally: 100
# Sieging chunks is impolite and makes a faction lose reputation
# Note: When a faction sieges a chunk, it loses reputation as well as increase the number of chunks claimed.
# Therefore, the power reduced in a siege is siege reputation loss + power required to claim a chunk
siege reputation loss: 500
#### Player
## Power of a faction depends on its members. When it loses members, its power drops.
# The power required for a faction to claim a chunk
power required to claim a chunk: 1000
# The power of a player increases every hour he is online (not necessarily a continuous hour)
power gained per online hour: 50
# The power of a player decreases if he has not been online that day ("day" calculated in the server's time zone)
power lost per offline FULL day: 40
# The power of a player increases when he kills a player or a mob
power gained per player kill: 60
power gained per mob kill:
  default: 5
  zombie pigman: 30
  creeper: 40
  skeleton: 30
  zombie: 20
# This counts the number of TINY slimes killed.
  slime: 2
  enderman: 40
# The power of a player decreases when he dies
power lost per death:
  default: 30
  killed by player: 50
  killed by monster: 50
  drowning: 35
  monster: 45
  explosion: 35
  lava: 40
  burning: 30
  falling: 10

############
## GAMEPLAY ##
############
## When a faction's power drops too low that no more chunks can be claimed, and in fact its power would not allow it to claim so many chunks, "power overdraft" occurs.
# When sieging is enabled, if a faction has power overdraft, other factions can siege any marginal chunks of the faction by walking in the chunk centre and claim the chunk like from wilderness.
enable sieging: false

## Members of other factions can only siege the marginal chunk if they walk inside enough. Define "inside enough" here.
# If the player is within this number of blocks from the chunk centre, allow them to siege the chunk.
siege radius: 4

## Players can set homes to teleport to their faction homes.
# This plugin allows multiple homes. What is the maximum number of homes allowed?
# Note: strange bugs may occur if players already started setting homes but then you decreased this value.
# This value must not exceed 255.
max homes: 1

## World loading
# PocketFactions generates a world if the world of a faction's claimed chunk doesn't exist. If you want to specify the seed, put it below.
level generation seed: null

## Faction defaults
# The following is a regular expression of the rule that limits faction names. If you don't understand regular expressions, leave this as it is.
faction naming rule: '#[A-Za-z0-9\-_]{@min,@max}#'
# The minimum length of the faction name
faction name min length: 3
# The maximum length (cannot be greater than 255)
faction name max length: 15
# If the faction name is rejected, send this message:
faction name reject message: Invalid faction name. The faction name must not be shorter than 3 characters or longer than 15 characters.

## Factions management
# Definition of activity
# Put one of the following here (case-insensitive):
# JOIN
# AUTH
# BUILD
faction activity definition: AUTH
# Disbanding inactive factions
# How long can a faction stay inactive (no any members successfully authenticating in the server) before getting automatically disbanded?
# The unit is hours.
faction inactive time: 168
# How often to check for inactive factions?
# The unit is minutes.
faction inactive check interval: 120
# Unlisting semi-inactive factions
# How long can a faction stay inactive (no any members successfully authenticating in the server) before getting unlisted?
# Note: The faction will be re-added to the list if it gets active again.
# The unit is hours.
faction semi-inactive time: 72

# Default permissions
default ranks:
- name: recruit
  id: 1
  permissions:
  - P_TP_HOME
  - P_DEPOSIT_MONEY
  - P_CHAT_ANNOUNCEMENT
  - P_NORM_FIGHT
  description: Default rank
- name: ally
  id: 2
  parent: 1
  permissions:
  - P_BUILD
- name: truce
  id: 3
  parent: 1
  permissions:
  - !P_NORM_FIGHT
- name: member
  id: 4
  parent: 1
  permissions:
  - P_BUILD
- name: builder
  id: 5
  parent: 4
  permissions:
  - P_BUILD_CENTRE
- name: official
  id: 6
  parent: 5
  permissions:
  - TODO # TODO
- name: admin
  id: 7
  parent: 6
  permissions:
  - TODO # TODO
- name: founder
  id: 8
  permissions:
  - P_ALL
founder rank: 8
default rank: 1
ally rank: 2
truce rank: 3

...
